# Generated by Django 5.0.6 on 2024-05-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_mytoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyToken',
            new_name='EmployeeToken',
        ),
    ]
